### ISSUE TITLE
Haakjes vergeten

### ISSUE THREAD

**Issue by bart314** [bart314/boterkaaseieren#7]
In het begin van de klasse wordt het doel van hiervan uitgelegd. In het voorbeeldbord dat hier wordt getoond, zijn haakjes-sluiten vergeten.

**Comment by marikevisser** [comment]
Kunnen die haakjes niet helemaal verdwijnen? Hebben ze een doel?

**Comment by marikevisser** [comment]
Ik pak deze op!

**Comment by Tsluiz** [comment]
wij doen ze al
